mqtt:
  client:
    protocol: 4      # MQTTv311
  connection:
    host: localhost
    port: 1883
    keepalive: 60
bridge:
  # ping pong
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: mqtt_video.msg:Image
    topic_from: /images
    topic_to: robot_to_awsiot
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: mqtt_video.msg:Image
    topic_from: both_directions
    topic_to: /chatter
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: geometry_msgs.msg:Twist
    topic_from: awsiot_to_robot
    topic_to: /cmd_vel
